/// generated by ts2fable and transformer
namespace FsHafas.Raw
/// <namespacedoc>
///   <summary>Types of raw hafas api generated from <a href="https://github.com/bergmannjg/hafas-client/blob/add-types-in-jsdoc/types-raw-api.ts">TS types</a></summary>
/// </namespacedoc>

open FsHafas.Client

#if FABLE_COMPILER
open Fable.Core
#endif


type RawPltf = { ``type``: string; txt: string }

type RawTrnCmpSX =
    { tcM: int option
      tcocX: array<int> option }

type RawDep =
    { locX: int option
      idx: int option
      dProdX: int option
      dPlatfS: string option
      dInR: bool option
      dTimeS: string option
      dProgType: string option
      dTrnCmpSX: RawTrnCmpSX option
      dTZOffset: int option
      ``type``: string option
      dTimeR: string option
      dCncl: bool option
      dPltfS: RawPltf option
      dPlatfR: string option
      dPltfR: RawPltf option }

type RawArr =
    { locX: int option
      idx: int option
      aPlatfS: string option
      aOutR: bool option
      aTimeS: string option
      aProgType: string option
      aTZOffset: int option
      ``type``: string option
      aTimeR: string option
      aCncl: bool option
      aPltfS: RawPltf option
      aPlatfR: string option
      aPltfR: RawPltf option }

type PubCh =
    { name: string
      fDate: string
      fTime: string
      tDate: string
      tTime: string }

type RawHim =
    { hid: string
      act: bool
      pub: string option
      head: string option
      lead: string option
      text: string option
      tckr: string option
      icoX: int
      prio: int
      fLocX: int option
      tLocX: int option
      prod: int option
      lModDate: string option
      lModTime: string option
      sDate: string option
      sTime: string option
      eDate: string option
      eTime: string option
      cat: int option
      pubChL: array<PubCh>
      edgeRefL: array<int> option
      regionRefL: array<int> option
      catRefL: array<int> option
      eventRefL: array<int> option
      affProdRefL: array<int> option
      comp: string option }

type RawMsg =
    { ``type``: string
      remX: int option
      fLocX: int option
      tLocX: int option
      fIdx: int option
      tIdx: int option
      himX: int option
      tagL: array<string> option }

type RawRem =
    { ``type``: string
      code: string
      prio: int option
      icoX: int option
      txtN: string option
      txtS: string option
      jid: string option }

type RawStop =
    { locX: int
      idx: int option
      dProdX: int option
      dInR: bool option
      dTimeS: string option
      dTimeR: string option
      dTZOffset: int option
      dCncl: bool option
      dInS: bool option
      dPlatfS: string option
      dPltfS: RawPltf option
      dPlatfR: string option
      dPltfR: RawPltf option
      dProgType: string option
      dDirTxt: string option
      dDirFlg: string option
      dTrnCmpSX: RawTrnCmpSX option
      aProdX: int option
      aPlatfS: string option
      aPltfS: RawPltf option
      aPlatfR: string option
      aPltfR: RawPltf option
      aOutR: bool option
      aTimeS: string option
      aTimeR: string option
      aTZOffset: int option
      aCncl: bool option
      aOutS: bool option
      aPlatfCh: bool option
      aProgType: string option
      ``type``: string option
      msgL: array<RawMsg> option
      remL: array<RawRem> option }

type PpLocRef = { ppIdx: int; locX: int }

type RawPoly =
    { delta: bool
      dim: int
      ``type``: string option
      crdEncYX: string
      crdEncZ: string option
      crdEncS: string
      crdEncF: string
      ppLocRefL: array<PpLocRef> option }

type PolyG = { polyXL: array<int> }

type RawAni =
    { mSec: array<int>
      proc: array<int>
      procAbs: array<int> option
      fLocX: array<int>
      tLocX: array<int>
      dirGeo: array<int>
      stcOutputX: array<int>
      polyG: PolyG option
      state: array<string>
      poly: RawPoly option }

type RawSDays =
    { fLocX: int option
      tLocX: int option
      sDaysR: string option
      sDaysI: string option
      sDaysB: string option }

type RawPolyG = { polyXL: array<int> }
type RawCrd = { x: int; y: int; z: int option }

type RawFreq =
    { minC: int option
      maxC: int option
      numC: int option
      jnyL: array<RawJny> option }

and RawJny =
    { jid: string
      prodX: int
      dirTxt: string option
      status: string option
      isRchbl: bool option
      ctxRecon: string option
      remL: array<RawRem> option
      msgL: array<RawMsg> option
      stbStop: RawStop option
      subscr: string option
      poly: RawPoly option
      stopL: array<RawStop> option
      date: string option
      sDaysL: array<RawSDays> option
      dTrnCmpSX: RawTrnCmpSX option
      polyG: RawPolyG option
      ani: RawAni option
      pos: RawCrd option 
      freq: RawFreq option }

type RawGis =
    { dist: int option
      depsS: string option }

type RawSec =
    { ``type``: string
      icoX: int option
      dep: RawDep
      arr: RawArr
      jny: RawJny option
      resState: string option
      resRecommendation: string option
      gis: RawGis option }

type RawSotCtxt =
    { cnLocX: int option
      calcDate: string
      jid: string option
      locMode: string
      pLocX: int option
      reqMode: string
      sectX: int option
      calcTime: string }

type Content = { ``type``: string; content: string }
type ExtCont = { content: Content }

type RawTicket =
    { name: string
      prc: int
      cur: string
      extCont: ExtCont }

type RawPrice = { amount: int option }

type RawFare =
    { price: RawPrice option
      isFromPrice: bool option
      isBookable: bool option
      isUpsell: bool option
      targetCtx: string option
      buttonText: string option
      name: string option
      ticketL: array<RawTicket> option }

type RawFareSet =
    { desc: string option
      fareL: array<RawFare> }

type RawTrfRes =
    { statusCode: string option
      fareSetL: array<RawFareSet> }

type RawOutCon =
    { cid: string
      date: string
      dur: string
      chg: int
      sDays: RawSDays
      dep: RawDep
      arr: RawArr
      secL: array<RawSec>
      ctxRecon: string
      trfRes: RawTrfRes option
      conSubscr: string
      resState: string option
      resRecommendation: string option
      recState: string
      sotRating: int option
      isSotCon: bool option
      showARSLink: bool option
      sotCtxt: RawSotCtxt option
      cksum: string
      msgL: array<RawMsg> option
      freq: RawFreq option }

type RawItem =
    { col: int
      row: int
      msgL: array<RawMsg> option
      remL: array<int> option }

type RawGrid =
    { nCols: int
      nRows: int
      itemL: array<RawItem>
      ``type``: string
      title: string }

type RawLoc =
    { lid: string option
      ``type``: string option
      name: string
      icoX: int option
      extId: string option
      state: string
      crd: RawCrd option
      pCls: int option
      entry: bool option
      mMastLocX: int option
      pRefL: array<int> option
      wt: int option
      entryLocL: array<int> option
      stopLocL: array<int> option
      msgL: array<RawMsg> option
      gridL: array<RawGrid> option
      isMainMast: bool option
      meta: bool option
      dist: int option
      dur: int option }

type RawProdCtx =
    { name: string option
      num: string option
      matchId: string option
      catOut: string option
      catOutS: string option
      catOutL: string option
      catIn: string option
      catCode: string option
      admin: string option
      lineId: string option }

type RawOp = { name: string; icoX: int }

type RawProd =
    { name: string
      number: string option
      icoX: int option
      oprX: int option
      prodCtx: RawProdCtx option
      cls: int option
      line: string option
      addName: string option }

type RawRGB = { r: int option; g: int; b: int }

type RawIco =
    { res: string option
      txt: string option
      text: string option
      txtS: string option
      fg: RawRGB option
      bg: RawRGB option }

type RawDir = { txt: string; flg: string option }
type RawTcoc = { c: string; r: int option }
type RawHimMsgCat = { id: int }

type IcoCrd =
    { x: int
      y: int
      ``type``: string option }

type RawHimMsgEdge =
    { fLocX: int option
      tLocX: int option
      dir: int option
      icoCrd: IcoCrd
      msgRefL: array<int> option
      icoX: int option }

type RawHimMsgEvent =
    { fLocX: int option
      tLocX: int option
      fDate: string
      fTime: string
      tDate: string
      tTime: string }

type RawCommon =
    { locL: array<RawLoc> option
      prodL: array<RawProd> option
      remL: array<RawRem> option
      icoL: array<RawIco> option
      opL: array<RawOp> option
      maxC: int option
      numC: int option
      himL: array<RawHim> option
      polyL: array<RawPoly> option
      dirL: array<RawDir> option
      tcocL: array<RawTcoc> option
      himMsgCatL: array<RawHimMsgCat> option
      himMsgEdgeL: array<RawHimMsgEdge> option
      himMsgEventL: array<RawHimMsgEvent> option }

type RawMatch =
    { field: string option
      state: string option
      locL: array<RawLoc> }

type RawPos = { locX: int; dur: int }

type RawLine =
    { lineId: string option
      prodX: int
      dirRefL: array<int> option
      jnyL: array<RawJny> option }

type RawResult =
    { common: RawCommon option
      msgL: array<RawHim> option
      ``type``: string option
      jnyL: array<RawJny> option
      outConL: array<RawOutCon> option
      outCtxScrB: string option
      outCtxScrF: string option
      planrtTS: string option
      ``match``: RawMatch option
      locL: array<RawLoc> option
      journey: RawJny option
      fpE: string option
      sD: string option
      sT: string option
      fpB: string option
      posL: array<RawPos> option
      lineL: array<RawLine> option }

type SvcRes =
    { meth: string
      err: string option
      errTxt: string option
      res: RawResult }

type RawResponse =
    { ver: string
      lang: string
      id: string option
      err: string option
      errTxt: string option
      svcResL: array<SvcRes> option }

type Cfg =
    { polyEnc: string
      rtMode: string option }

type Loc =
    { ``type``: string
      name: string option
      lid: string option }

type LocViaInput = { loc: Loc }

type LocMatchInput =
    { loc: Loc
      maxLoc: int
      field: string }

type LocMatchRequest = { input: LocMatchInput }
type LineMatchRequest = { input: string }

type JourneyDetailsRequest =
    { jid: string
      name: string
      getPolyline: bool }

type JnyFltr =
    { ``type``: string
      mode: string
      value: string option
      meta: string option }

type TvlrProf =
    { ``type``: string
      redtnCard: int option }

type TrfReq =
    { jnyCl: int
      tvlrProf: array<TvlrProf>
      cType: string }

type StationBoardRequest =
    { ``type``: string
      date: string
      time: string
      stbLoc: Loc
      jnyFltrL: array<JnyFltr>
      dur: int }

type HimSearchRequest =
    { himFltrL: array<JnyFltr>
      getPolyline: bool
      maxNum: int
      dateB: string
      timeB: string }

type ReconstructionRequest =
    { getIST: bool
      getPasslist: bool
      getPolyline: bool
      getTariff: bool
      ctxRecon: string option }

type LocData =
    { loc: Loc
      ``type``: string
      date: string
      time: string }

type SearchOnTripRequest =
    { sotMode: string
      jid: string
      locData: LocData
      arrLocL: array<Loc>
      jnyFltrL: array<JnyFltr>
      getPasslist: bool
      getPolyline: bool
      minChgTime: int
      getTariff: bool }

type TripSearchRequest =
    { getPasslist: bool
      maxChg: int
      minChgTime: int
      depLocL: array<Loc>
      viaLocL: array<LocViaInput> option
      arrLocL: array<Loc>
      jnyFltrL: array<JnyFltr>
      gisFltrL: array<JnyFltr>
      getTariff: bool
      ushrp: bool
      getPT: bool
      getIV: bool
      getPolyline: bool
      outDate: string
      outTime: string
      numF: int
      outFrwd: bool
      trfReq: TrfReq option }

type JourneyMatchRequest = { input: string; date: string option }
type RawcCrd = { x: int; y: int }

type RawRing =
    { cCrd: RawcCrd
      maxDist: int
      minDist: int }

type LocGeoPosRequest =
    { ring: RawRing
      locFltrL: array<JnyFltr>
      getPOIs: bool
      getStops: bool
      maxLoc: int }

type LocGeoReachRequest =
    { loc: Loc
      maxDur: int
      maxChg: int
      date: string
      time: string
      period: int
      jnyFltrL: array<JnyFltr> }

type LocDetailsRequest = { locL: array<Loc> }
type ServerInfoRequest = obj
type RawRect = { llCrd: RawCrd; urCrd: RawCrd }

type JourneyGeoPosRequest =
    { maxJny: int
      onlyRT: bool
      date: string
      time: string
      rect: RawRect
      perSize: int
      perStep: int
      ageOfReport: bool
      jnyFltrL: array<JnyFltr>
      trainPosMode: string }

type SvcReq =
    { cfg: Cfg
      meth: string
      req: U14<LocMatchRequest, TripSearchRequest, JourneyDetailsRequest, StationBoardRequest, ReconstructionRequest, JourneyMatchRequest, LocGeoPosRequest, LocGeoReachRequest, LocDetailsRequest, JourneyGeoPosRequest, HimSearchRequest, LineMatchRequest, ServerInfoRequest, SearchOnTripRequest> }

type RawRequestClient =
    { id: string
      v: string
      ``type``: string
      name: string }

type RawRequestAuth = { ``type``: string; aid: string }

type RawRequest =
    { lang: string
      svcReqL: array<SvcReq>
      client: RawRequestClient
      ext: string
      ver: string
      auth: RawRequestAuth }
