namespace FsHafas.Profiles.OebbConfig

module internal Products =

    open FsHafas.Client

    let products: ProductType [] =
        [| { id = "nationalExpress"
             mode = Train
             name = "InterCityExpress & RailJet"
             short = "ICE/RJ"
             bitmasks = [| 1 |]
             ``default`` = true }
           { id = "national"
             mode = Train
             name = "InterCity & EuroCity"
             short = "IC/EC"
             bitmasks = [| 2; 4 |]
             ``default`` = true }
           { id = "interregional"
             mode = Train
             name = "Durchgangszug & EuroNight"
             short = "D/EN"
             bitmasks = [| 8; 4096 |]
             ``default`` = true }
           { id = "regional"
             mode = Train
             name = "Regional & RegionalExpress"
             short = "R/REX"
             bitmasks = [| 16 |]
             ``default`` = true }
           { id = "suburban"
             mode = Train
             name = "S-Bahn"
             short = "S"
             bitmasks = [| 32 |]
             ``default`` = true }
           { id = "bus"
             mode = Bus
             name = "Bus"
             short = "B"
             bitmasks = [| 64 |]
             ``default`` = true }
           { id = "ferry"
             mode = Watercraft
             name = "Ferry"
             short = "F"
             bitmasks = [| 128 |]
             ``default`` = true }
           { id = "subway"
             mode = Train
             name = "U-Bahn"
             short = "U"
             bitmasks = [| 256 |]
             ``default`` = true }
           { id = "tram"
             mode = Train
             name = "Tram"
             short = "T"
             bitmasks = [| 512 |]
             ``default`` = true }
           { id = "onCall"
             mode = Taxi
             name = "on-call transit, lifts, etc"
             short = "on-call/lift"
             bitmasks = [| 2048 |]
             ``default`` = true } |]
